### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:23654

### ISSUE THREAD

**Issue by mrsydster** [hhaidar/deckdev#1]
Thanks for creating this tool! Really useful. 

However, I installed it and run `deckdev watch path/to/plugin` and get the following error. 

```
deckdev watch Sources/com.streamdoctors.symetrix.sdPlugin/
    Error: connect ECONNREFUSED 127.0.0.1:23654
    Code: ECONNREFUSED
```

Am I doing something wrong?

**Comment by hhaidar** [comment]
Hey there,

You'll need to enable the debugger:

Type `regedit.exe` in the start menu search and then:

> on Windows, you will need to add a DWORD html_remote_debugging_enabled with value 1 in the registry @ HKEY_CURRENT_USER\Software\Elgato Systems GmbH\StreamDeck.

Relaunch the Stream Deck app and verify that http://localhost:23654/ shows a chrome debugger.

via: https://developer.elgato.com/documentation/stream-deck/sdk/create-your-own-plugin/#debugging

**Comment by hhaidar** [comment]
I'll add instructions and a more helpful error message in the next release.

I'm thinking though... maybe I should make the registry change as a built-in command? Perhaps something like this:

```
deckdev debugger enable
deckdev debugger disable
```

**Comment by mrsydster** [comment]
I knew it was something I missed myself..! Thanks! 

Yeah the solutions you mentioned would be great!

**Comment by hhaidar** [comment]
Added a command to disable/enable debugger without fiddling with the registry:

```
deckdev debugger enable
```

See:
* https://github.com/hhaidar/deckdev#deckdev-debugger-action
* https://github.com/hhaidar/deckdev/commit/8e7d5626d7d819e512bbb5e730cdd3091603331c
